# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 359e237d95cb7a4b18740063ee01658b9799868c8e0bdc725b7a90c9937ce5db898e1444e1a624f842a87b1631a8cd9c783b6ddd2e124d770363d7164d282341

test:
  secret_key_base: 7ee381f85daa0bb98c9e9525529921e2b5a4f7d428b768704ab78843f1082a3ef007cddfabd50c03ce97af217526a8e95ee0c1aae2404459bd81b40abe0e8a75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
